# Generated by Django 4.1.7 on 2023-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mascota', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=30)),
                ('tipo_de_mascota', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField(max_length=2)),
                ('vacunas', models.CharField(max_length=500)),
                ('comentarios', models.CharField(max_length=2000)),
            ],
        ),
    ]
